/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Slate Framer extraction — exact mapping (do not change hexes)
        bg: '#09090b',
        primary: {
          DEFAULT: '#5e7ce2',
          foreground: '#ffffff',
        },
        surface: {
          DEFAULT: '#f4f4f5',
          foreground: '#09090b',
        },
        neutral: {
          DEFAULT: '#a1a1aa',
          muted: '#71717a',
        },
        accent: {
          DEFAULT: '#2d2d34',
          foreground: '#f4f4f5',
        },
        slate: {
          bg: '#09090b',
          primary: '#5e7ce2',
          surface: '#f4f4f5',
          neutral: '#a1a1aa',
          'neutral-muted': '#71717a',
          accent: '#2d2d34',
        },
        // Legacy doom palette kept for backwards compat — prefer slate tokens above
        doom: {
          bg: '#0c0d0e',
          surface: '#141618',
          card: '#1a1d20',
          border: '#2a2e33',
          'border-bright': '#3f454c',
          text: '#e2e8f0',
          muted: '#8b949e',
          red: '#dc2626',
          'red-bright': '#ef4444',
          'red-dark': '#991b1b',
          amber: '#f59e0b',
          'amber-bright': '#fbbf24',
          green: '#10b981',
          'green-bright': '#34d399',
          cyan: '#06b6d4',
          blue: '#3b82f6',
        },
      },
      // 8px spacing system — Tailwind default is 4px base (1=0.25rem=4px, 2=0.5rem=8px)
      // Explicitly defined so spacing scale is pinned to 8px grid
      spacing: {
        px: '1px',
        0: '0px',
        0.5: '0.125rem',
        1: '0.25rem',
        1.5: '0.375rem',
        2: '0.5rem',
        2.5: '0.625rem',
        3: '0.75rem',
        3.5: '0.875rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
        11: '2.75rem',
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        28: '7rem',
        32: '8rem',
      },
      borderRadius: {
        none: '0px',
        sm: '2px',
        div: '2px',
        DEFAULT: '8px',
        md: '8px',
        card: '8px',
        button: '8px',
        lg: '12px',
        outer: '12px',
        xl: '12px',
        '2xl': '16px',
        full: '9999px',
      },
      fontFamily: {
        sans: ['var(--font-geist)', 'Geist', 'Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        geist: ['var(--font-geist)', 'Geist', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'],
      },
      transitionDuration: {
        DEFAULT: '0.001s',
        instant: '0.001s',
      },
      transitionTimingFunction: {
        DEFAULT: 'ease',
        slate: 'ease',
      },
    },
  },
  plugins: [],
}
