package main

import (
	"bytes"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"rnt-launcher/internal/idgames/seed"
)

func main() {
	entries := buildSeedEntries()
	data, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error marshaling catalog JSON: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	gw, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating gzip writer: %v\n", err)
		os.Exit(1)
	}

	if _, err := gw.Write(data); err != nil {
		fmt.Fprintf(os.Stderr, "Error compressing catalog data: %v\n", err)
		os.Exit(1)
	}
	if err := gw.Close(); err != nil {
		fmt.Fprintf(os.Stderr, "Error closing gzip writer: %v\n", err)
		os.Exit(1)
	}

	outPath := filepath.Join("internal", "idgames", "seed", "catalog.json.gz")
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating seed directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated %s (%d entries, %d bytes uncompressed, %d bytes gzipped)\n",
		outPath, len(entries), len(data), buf.Len())
}

func buildSeedEntries() []seed.Entry {
	return []seed.Entry{
		{
			ID:          19342,
			Title:       "Eviternity",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "eviternity.zip",
			Size:        75497472,
			Age:         1549756800,
			Date:        "2019-02-10",
			Author:      "Dragonfly and various artists",
			Description: "Eviternity is a 32-level megawad designed to commemorate Doom's 25th birthday. Divided into 6 distinct chapters, featuring OTEX textures by ukiro.",
			Rating:      4.85,
			Votes:       840,
		},
		{
			ID:          18454,
			Title:       "Ancient Aliens",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "aaliens.zip",
			Size:        52428800,
			Age:         1463961600,
			Date:        "2016-05-23",
			Author:      "skillsaw and various artists",
			Description: "Ancient Aliens is a 32-level megawad featuring custom textures, vibrant neon colors, and original music by Stuart Rynn and stewboy.",
			Rating:      4.79,
			Votes:       720,
		},
		{
			ID:          12158,
			Title:       "Scythe",
			Dir:         "levels/doom2/megawads",
			Filename:    "scythe.zip",
			Size:        2621440,
			Age:         1052611200,
			Date:        "2003-05-11",
			Author:      "Erik Alm",
			Description: "32 fast-paced, high-intensity levels emphasizing speed, tight layouts, and pure adrenaline.",
			Rating:      4.65,
			Votes:       610,
		},
		{
			ID:          14197,
			Title:       "Scythe 2",
			Dir:         "levels/doom2/megawads",
			Filename:    "scythe2.zip",
			Size:        10485760,
			Age:         1117929600,
			Date:        "2005-06-05",
			Author:      "Erik Alm",
			Description: "The 32-level sequel to Scythe taking you across Gothic castles, jungle ruins, and Martian techbases with custom Afrit monsters.",
			Rating:      4.81,
			Votes:       790,
		},
		{
			ID:          18073,
			Title:       "Valiant",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "valiant.zip",
			Size:        62914560,
			Age:         1429920000,
			Date:        "2015-04-25",
			Author:      "skillsaw",
			Description: "A 32-level megawad for MBF-compatible ports. Fast, punchy combat with custom DeHackEd weapon modifications and unique monster variants.",
			Rating:      4.82,
			Votes:       670,
		},
		{
			ID:          18128,
			Title:       "Sunlust",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "sunlust.zip",
			Size:        33554432,
			Age:         1434844800,
			Date:        "2015-06-21",
			Author:      "Ribbiks and Dannebubnga",
			Description: "A set of 32 challenging and visually opulent maps designed for Boom-compatible source ports.",
			Rating:      4.78,
			Votes:       540,
		},
		{
			ID:          15631,
			Title:       "Sunder",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "sunder.zip",
			Size:        18874368,
			Age:         1243123200,
			Date:        "2009-05-24",
			Author:      "Insane_Gazebo",
			Description: "Monolithic, visually astonishing architectural slaughter maps testing the boundaries of source ports.",
			Rating:      4.55,
			Votes:       480,
		},
		{
			ID:          16999,
			Title:       "Back to Saturn X Episode 1: Get Out Of My Stations",
			Dir:         "levels/doom2/megawads",
			Filename:    "btsx_e1.zip",
			Size:        29360128,
			Age:         1354320000,
			Date:        "2012-12-01",
			Author:      "The BTSX Team",
			Description: "Full vanilla-compatible 27-map adventure on the satellite moon Saturn X with custom paletted graphics and an iconic soundtrack.",
			Rating:      4.76,
			Votes:       590,
		},
		{
			ID:          17772,
			Title:       "Back to Saturn X Episode 2: Tower in the Fountain of Sparks",
			Dir:         "levels/doom2/megawads",
			Filename:    "btsx_e2.zip",
			Size:        35651584,
			Age:         1408060800,
			Date:        "2014-08-15",
			Author:      "The BTSX Team",
			Description: "The monumental second installment of the BTSX trilogy spanning high-tech research centers, alien outposts, and abandoned ruins.",
			Rating:      4.80,
			Votes:       510,
		},
		{
			ID:          19445,
			Title:       "SIGIL",
			Dir:         "levels/doom/Ports/s-u",
			Filename:    "sigil_v1_21.zip",
			Size:        3145728,
			Age:         1558483200,
			Date:        "2019-05-22",
			Author:      "John Romero",
			Description: "The official spiritual successor to the fourth episode of Ultimate Doom, handcrafted by original creator John Romero with music by Buckethead.",
			Rating:      4.42,
			Votes:       910,
		},
		{
			ID:          11751,
			Title:       "Alien Vendetta",
			Dir:         "levels/doom2/megawads",
			Filename:    "av.zip",
			Size:        16777216,
			Age:         1038528000,
			Date:        "2002-11-29",
			Author:      "Anders Johnsen, Kim Bach and contributors",
			Description: "One of the greatest Doom II megawads ever released, featuring 32 sprawling, breathtaking maps and intense combat setups.",
			Rating:      4.72,
			Votes:       850,
		},
		{
			ID:          7929,
			Title:       "Hell Revealed",
			Dir:         "levels/doom2/megawads",
			Filename:    "hr.zip",
			Size:        6291456,
			Age:         862617600,
			Date:        "1997-05-02",
			Author:      "Yonatan Donner and Haggay Niv",
			Description: "A milestone 32-level megawad that defined hardcore challenge mapping and spawned the modern slaughter genre.",
			Rating:      4.48,
			Votes:       690,
		},
		{
			ID:          12592,
			Title:       "Hell Revealed II",
			Dir:         "levels/doom2/megawads",
			Filename:    "hr2final.zip",
			Size:        15728640,
			Age:         1072828800,
			Date:        "2003-12-31",
			Author:      "The HR2 Team",
			Description: "The brutal 32-map continuation of Hell Revealed, pushing monster counts and claustrophobic pressure to new heights.",
			Rating:      4.21,
			Votes:       410,
		},
		{
			ID:          8879,
			Title:       "Requiem",
			Dir:         "levels/doom2/megawads",
			Filename:    "requiem.zip",
			Size:        8388608,
			Age:         867974400,
			Date:        "1997-07-04",
			Author:      "The Requiem Team",
			Description: "Classic 32-level community collaboration featuring mapping from Iikka Keränen, Dario Casali, and Matthias Worch.",
			Rating:      4.52,
			Votes:       580,
		},
		{
			ID:          5462,
			Title:       "Memento Mori",
			Dir:         "levels/doom2/megawads",
			Filename:    "mm.zip",
			Size:        8388608,
			Age:         818553600,
			Date:        "1995-12-10",
			Author:      "Denis & Thomas Möller and contributors",
			Description: "The first true community megawad milestone, establishing cooperative mapping and custom soundtracks.",
			Rating:      4.46,
			Votes:       520,
		},
		{
			ID:          6710,
			Title:       "Memento Mori II",
			Dir:         "levels/doom2/megawads",
			Filename:    "mm2.zip",
			Size:        10485760,
			Age:         849139200,
			Date:        "1996-11-28",
			Author:      "The MMT Team",
			Description: "Masterful sequel to Memento Mori, celebrated for its brilliant level layouts, custom MIDIs, and high replayability.",
			Rating:      4.61,
			Votes:       550,
		},
		{
			ID:          10452,
			Title:       "Batman DOOM",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "batman.zip",
			Size:        14680064,
			Age:         923529600,
			Date:        "1999-04-08",
			Author:      "ACE Team Software",
			Description: "Iconic Total Conversion turning Doom into a Gotham City adventure with custom weapons, villains, and sound effects.",
			Rating:      4.64,
			Votes:       490,
		},
		{
			ID:          13000,
			Title:       "Action Doom",
			Dir:         "levels/doom2/Ports/a-c",
			Filename:    "action.zip",
			Size:        20971520,
			Age:         1089936000,
			Date:        "2004-07-16",
			Author:      "Scuba Steve and team",
			Description: "Side-scrolling arcade and run-and-gun tribute built completely in ZDoom with hand-drawn graphics and branching paths.",
			Rating:      4.58,
			Votes:       420,
		},
		{
			ID:          17822,
			Title:       "The Golden Souls",
			Dir:         "levels/doom2/Ports/g-i",
			Filename:    "goldensouls.pk3",
			Size:        134217728,
			Age:         1411516800,
			Date:        "2014-09-24",
			Author:      "Batandy",
			Description: "Super Mario 64 inspired adventure total conversion for GZDoom featuring world hubs, coin collecting, and colorful paintings.",
			Rating:      4.74,
			Votes:       380,
		},
		{
			ID:          17409,
			Title:       "Pirate Doom!",
			Dir:         "levels/doom2/Ports/p-r",
			Filename:    "pirates.pk3",
			Size:        94371840,
			Age:         1379721600,
			Date:        "2013-09-21",
			Author:      "Arch",
			Description: "Swashbuckling 18-level GZDoom campaign filled with tropical archipelagos, pirate galleons, and undead buccaneers.",
			Rating:      4.77,
			Votes:       410,
		},
		{
			ID:          17578,
			Title:       "Going Down",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "gd.zip",
			Size:        12582912,
			Age:         1385424000,
			Date:        "2013-11-26",
			Author:      "mouldy (Cyriak Harris)",
			Description: "A chaotic descent through a 32-floor corporate skyscraper, descending from the penthouse into madness and hell.",
			Rating:      4.75,
			Votes:       630,
		},
		{
			ID:          15589,
			Title:       "Plutonia 2",
			Dir:         "levels/doom2/megawads",
			Filename:    "pl2.zip",
			Size:        18874368,
			Age:         1230681600,
			Date:        "2008-12-31",
			Author:      "The Plutonia 2 Team",
			Description: "The definitive community-crafted sequel to the Casali brothers' Plutonia Experiment with relentless trap designs.",
			Rating:      4.68,
			Votes:       570,
		},
		{
			ID:          16035,
			Title:       "Speed of Doom",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "sodfinal.zip",
			Size:        16777216,
			Age:         1270080000,
			Date:        "2010-04-01",
			Author:      "Josh Sealy and Darkwave0000",
			Description: "A breathtaking 33-map Boom megawad featuring high-speed gameplay, vivid lighting, and memorable setpieces.",
			Rating:      4.71,
			Votes:       460,
		},
		{
			ID:          16933,
			Title:       "Community Chest 4",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "cchest4.zip",
			Size:        41943040,
			Age:         1343779200,
			Date:        "2012-08-01",
			Author:      "The Community Chest Team",
			Description: "The fourth chapter of the premier Boom mapping showcase featuring contributions from today's top tier authors.",
			Rating:      4.62,
			Votes:       440,
		},
		{
			ID:          12695,
			Title:       "Deus Vult",
			Dir:         "levels/doom2/Ports/d-f",
			Filename:    "dv.zip",
			Size:        12582912,
			Age:         1075593600,
			Date:        "2004-02-01",
			Author:      "Huy Pham",
			Description: "Legendary cathedral map of incomprehensible scale and architectural opulence, setting a new bar for visual detail.",
			Rating:      4.60,
			Votes:       530,
		},
		{
			ID:          15286,
			Title:       "Deus Vult II",
			Dir:         "levels/doom2/Ports/d-f",
			Filename:    "dvii-1i.zip",
			Size:        68157440,
			Age:         1207699200,
			Date:        "2008-04-09",
			Author:      "Huy Pham and contributors",
			Description: "Monumental journey traversing Greco-Roman temples, neo-Tokyo techbases, and subterranean catacombs.",
			Rating:      4.74,
			Votes:       620,
		},
		{
			ID:          14947,
			Title:       "Knee-Deep in ZDoom",
			Dir:         "levels/doom/Ports/j-l",
			Filename:    "kdizd_12.pk3",
			Size:        73400320,
			Age:         1184976000,
			Date:        "2007-07-21",
			Author:      "The KDiZD Team",
			Description: "Groundbreaking ZDoom overhaul of Episode 1 with 3D floors, particle systems, stealth monsters, and cutscenes.",
			Rating:      4.49,
			Votes:       610,
		},
		{
			ID:          19145,
			Title:       "Final Doomer",
			Dir:         "combos/Ports",
			Filename:    "final_doomer_v5.pk3",
			Size:        89128960,
			Age:         1529107200,
			Date:        "2018-06-16",
			Author:      "Sgt_Mark_IV, Yholl and team",
			Description: "Class-based weapon mod featuring unique weapon sets custom tailored for TNT, Plutonia, Alien Vendetta, Ancient Aliens, and more.",
			Rating:      4.82,
			Votes:       390,
		},
		{
			ID:          17957,
			Title:       "Smooth Doom",
			Dir:         "graphics",
			Filename:    "smoothdoom.pk3",
			Size:        15728640,
			Age:         1420761600,
			Date:        "2015-01-09",
			Author:      "Gifty",
			Description: "Smooth high-framerate animations for all weapons and monsters while retaining 100% pure vanilla mechanics and feel.",
			Rating:      4.88,
			Votes:       710,
		},
		{
			ID:          18451,
			Title:       "Japanese Community Doom Project",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "jcdp.zip",
			Size:        37748736,
			Age:         1460332800,
			Date:        "2016-04-11",
			Author:      "Japanese Doom Community",
			Description: "32 levels of fresh, imaginative gameplay and visual variety celebrating the Japanese Doom mapping scene.",
			Rating:      4.69,
			Votes:       350,
		},
		{
			ID:          15873,
			Title:       "Harmony",
			Dir:         "levels/doom2/Ports/g-i",
			Filename:    "harmony.zip",
			Size:        33554432,
			Age:         1257033600,
			Date:        "2009-11-01",
			Author:      "Thomas van der Velden",
			Description: "Complete standalone 13-level total conversion featuring entirely original claymation-style sprites and post-apocalyptic lore.",
			Rating:      4.67,
			Votes:       320,
		},
		{
			ID:          19208,
			Title:       "REKKR",
			Dir:         "levels/doom/Ports/megawads",
			Filename:    "rekkr_v1_16.zip",
			Size:        27262976,
			Age:         1531785600,
			Date:        "2018-07-17",
			Author:      "Revae and team",
			Description: "Nordic Celtic dark fantasy total conversion with completely unique sprites, sounds, weapons, and maps.",
			Rating:      4.83,
			Votes:       430,
		},
		{
			ID:          19207,
			Title:       "Ashes 2063",
			Dir:         "levels/doom2/Ports/a-c",
			Filename:    "ashes2063.pk3",
			Size:        157286400,
			Age:         1537488000,
			Date:        "2018-09-21",
			Author:      "Vostyok",
			Description: "Post-apocalyptic survival shooter TC featuring merchant trading, motorcycle driving, inventory management, and radio chatter.",
			Rating:      4.91,
			Votes:       580,
		},
		{
			ID:          19163,
			Title:       "Struggle: Antaresian Legacy",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "struggle.zip",
			Size:        37748736,
			Age:         1535068800,
			Date:        "2018-08-24",
			Author:      "antares031",
			Description: "A stylish 33-map adventure with custom plasma weaponry, high-energy soundtrack, and sleek alien technology aesthetics.",
			Rating:      4.79,
			Votes:       380,
		},
		{
			ID:          19688,
			Title:       "Bloom",
			Dir:         "levels/doom2/Ports/a-c",
			Filename:    "bloom_v1.pk3",
			Size:        209715200,
			Age:         1572566400,
			Date:        "2019-11-01",
			Author:      "Bloom Team",
			Description: "A crossover total conversion combining the universes and arsenals of Blood and Doom into an intertwined cosmic horror.",
			Rating:      4.84,
			Votes:       340,
		},
		{
			ID:          19692,
			Title:       "Doom Zero",
			Dir:         "levels/doom2/megawads",
			Filename:    "doomzero.zip",
			Size:        20971520,
			Age:         1575849600,
			Date:        "2019-12-09",
			Author:      "Darragh Matthew (DASI-I)",
			Description: "A 32-level vanilla megawad featuring new branching puzzles, alpha-inspired enemies, and clever sector tricks.",
			Rating:      4.62,
			Votes:       470,
		},
		{
			ID:          19702,
			Title:       "Syringe",
			Dir:         "levels/doom2/Ports/s-u",
			Filename:    "syringe.zip",
			Size:        14680064,
			Age:         1577318400,
			Date:        "2019-12-26",
			Author:      "Tarnsman, Pavera, Ralphis, Marcaek",
			Description: "Surreal 7-map episode blending gothic dreamscapes, puzzle combat, and striking custom palette manipulation.",
			Rating:      4.73,
			Votes:       310,
		},
		{
			ID:          19705,
			Title:       "Finely Crafted Fetish Film",
			Dir:         "levels/doom2/Ports/d-f",
			Filename:    "fcff.zip",
			Size:        8388608,
			Age:         1577491200,
			Date:        "2019-12-28",
			Author:      "Ribbiks",
			Description: "Seven intricate, bite-sized puzzle slaughter challenges boasting trademark Ribbiks geometric perfection and neon pastel hues.",
			Rating:      4.76,
			Votes:       290,
		},
		{
			ID:          20265,
			Title:       "Heartland",
			Dir:         "levels/doom2/Ports/g-i",
			Filename:    "heartland.zip",
			Size:        47185920,
			Age:         1618790400,
			Date:        "2021-04-19",
			Author:      "skillsaw",
			Description: "Groundbreaking 7-map episode designed specifically for the Eternity Engine utilizing portals, 3D slopes, and linked spaces.",
			Rating:      4.92,
			Votes:       410,
		},
		{
			ID:          20299,
			Title:       "Auger;Zenith",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "augerzenith.zip",
			Size:        67108864,
			Age:         1626220800,
			Date:        "2021-07-14",
			Author:      "Doomer Boards Community",
			Description: "Cyberpunk neon megawad set in a sprawling dystopian rain-slicked mega-city with custom textures and synthwave tracks.",
			Rating:      4.85,
			Votes:       360,
		},
		{
			ID:          20300,
			Title:       "Lullaby",
			Dir:         "levels/doom2/Ports/j-l",
			Filename:    "lullaby.zip",
			Size:        16777216,
			Age:         1626825600,
			Date:        "2021-07-21",
			Author:      "Danlex",
			Description: "A single colossal dreamlike fantasy cathedral level bathed in cerulean hues and delicate gothic filigree.",
			Rating:      4.87,
			Votes:       320,
		},
		{
			ID:          19905,
			Title:       "Rowdy Rudy II: POWERTRIP",
			Dir:         "levels/doom2/Ports/megawads",
			Filename:    "rudy2.zip",
			Size:        31457280,
			Age:         1591833600,
			Date:        "2020-06-11",
			Author:      "Doomkid",
			Description: "High-octane retro action episode featuring custom assault rifles, flamethrowers, and classic 90s action-movie attitude.",
			Rating:      4.78,
			Votes:       340,
		},
		{
			ID:          20288,
			Title:       "Nostalgia",
			Dir:         "levels/doom2/megawads",
			Filename:    "nostalgia.zip",
			Size:        8388608,
			Age:         1624060800,
			Date:        "2021-06-19",
			Author:      "mykol",
			Description: "A 32-level vanilla compatible love letter to the early mapping styles of the 1990s with modern combat balancing.",
			Rating:      4.65,
			Votes:       280,
		},
		{
			ID:          20560,
			Title:       "Anomaly Report",
			Dir:         "levels/doom2/megawads",
			Filename:    "anomrep.zip",
			Size:        15728640,
			Age:         1649635200,
			Date:        "2022-04-11",
			Author:      "valkiriforce",
			Description: "32 compact, finely tuned classic maps filled with ingenious secrets, dynamic traps, and balanced UV pistol starts.",
			Rating:      4.80,
			Votes:       310,
		},
		{
			ID:          20748,
			Title:       "MyHouse.wad",
			Dir:         "levels/doom2/Ports/m-o",
			Filename:    "myhouse.pk3",
			Size:        68157440,
			Age:         1677801600,
			Date:        "2023-03-03",
			Author:      "Veddge",
			Description: "Viral psychological horror masterpiece utilizing GZDoom portals and scripting to craft an uncanny, shape-shifting suburban reality.",
			Rating:      4.96,
			Votes:       1420,
		},
	}
}
