// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEngine(arg1) {
  return window['go']['main']['App']['AddEngine'](arg1);
}

export function AddIWAD(arg1) {
  return window['go']['main']['App']['AddIWAD'](arg1);
}

export function AddModToProfile(arg1, arg2) {
  return window['go']['main']['App']['AddModToProfile'](arg1, arg2);
}

export function CheckModUpdates() {
  return window['go']['main']['App']['CheckModUpdates']();
}

export function ClearLaunchHistory() {
  return window['go']['main']['App']['ClearLaunchHistory']();
}

export function ClearSystemLogs() {
  return window['go']['main']['App']['ClearSystemLogs']();
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function ContinueProfileSave(arg1) {
  return window['go']['main']['App']['ContinueProfileSave'](arg1);
}

export function CreateDesktopShortcut(arg1) {
  return window['go']['main']['App']['CreateDesktopShortcut'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateProfileFromTemplate(arg1) {
  return window['go']['main']['App']['CreateProfileFromTemplate'](arg1);
}

export function CreateProfileSnapshot(arg1, arg2) {
  return window['go']['main']['App']['CreateProfileSnapshot'](arg1, arg2);
}

export function DeleteEngine(arg1) {
  return window['go']['main']['App']['DeleteEngine'](arg1);
}

export function DeleteIWAD(arg1) {
  return window['go']['main']['App']['DeleteIWAD'](arg1);
}

export function DeleteMod(arg1) {
  return window['go']['main']['App']['DeleteMod'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DetectEngineVersion(arg1) {
  return window['go']['main']['App']['DetectEngineVersion'](arg1);
}

export function DownloadIdgamesArchive(arg1) {
  return window['go']['main']['App']['DownloadIdgamesArchive'](arg1);
}

export function DownloadIdgamesMod(arg1) {
  return window['go']['main']['App']['DownloadIdgamesMod'](arg1);
}

export function DuplicateProfile(arg1, arg2) {
  return window['go']['main']['App']['DuplicateProfile'](arg1, arg2);
}

export function EnsureEngine(arg1, arg2) {
  return window['go']['main']['App']['EnsureEngine'](arg1, arg2);
}

export function ExportLibraryBackup() {
  return window['go']['main']['App']['ExportLibraryBackup']();
}

export function ExportProfileBundle(arg1) {
  return window['go']['main']['App']['ExportProfileBundle'](arg1);
}

export function ExportProfileYAML(arg1) {
  return window['go']['main']['App']['ExportProfileYAML'](arg1);
}

export function FindDuplicateMods() {
  return window['go']['main']['App']['FindDuplicateMods']();
}

export function GetActiveLaunches() {
  return window['go']['main']['App']['GetActiveLaunches']();
}

export function GetEngine(arg1) {
  return window['go']['main']['App']['GetEngine'](arg1);
}

export function GetHistoryStats() {
  return window['go']['main']['App']['GetHistoryStats']();
}

export function GetIWAD(arg1) {
  return window['go']['main']['App']['GetIWAD'](arg1);
}

export function GetIdgamesCuratedShowcase() {
  return window['go']['main']['App']['GetIdgamesCuratedShowcase']();
}

export function GetLaunchLogs(arg1, arg2) {
  return window['go']['main']['App']['GetLaunchLogs'](arg1, arg2);
}

export function GetMissingDependencies(arg1) {
  return window['go']['main']['App']['GetMissingDependencies'](arg1);
}

export function GetMod(arg1) {
  return window['go']['main']['App']['GetMod'](arg1);
}

export function GetModArtwork(arg1) {
  return window['go']['main']['App']['GetModArtwork'](arg1);
}

export function GetModUsageCounts() {
  return window['go']['main']['App']['GetModUsageCounts']();
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfileConflicts(arg1) {
  return window['go']['main']['App']['GetProfileConflicts'](arg1);
}

export function GetProfileSaveDir(arg1) {
  return window['go']['main']['App']['GetProfileSaveDir'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemLogs() {
  return window['go']['main']['App']['GetSystemLogs']();
}

export function ImportLibraryBackup(arg1) {
  return window['go']['main']['App']['ImportLibraryBackup'](arg1);
}

export function ImportModFile(arg1) {
  return window['go']['main']['App']['ImportModFile'](arg1);
}

export function ImportModFromURL(arg1) {
  return window['go']['main']['App']['ImportModFromURL'](arg1);
}

export function ImportProfileBundle(arg1) {
  return window['go']['main']['App']['ImportProfileBundle'](arg1);
}

export function ImportProfileShareCode(arg1) {
  return window['go']['main']['App']['ImportProfileShareCode'](arg1);
}

export function ImportProfileYAML(arg1) {
  return window['go']['main']['App']['ImportProfileYAML'](arg1);
}

export function ImportProfileZDL(arg1) {
  return window['go']['main']['App']['ImportProfileZDL'](arg1);
}

export function InspectIWADFile(arg1) {
  return window['go']['main']['App']['InspectIWADFile'](arg1);
}

export function InspectMod(arg1) {
  return window['go']['main']['App']['InspectMod'](arg1);
}

export function IsScanning() {
  return window['go']['main']['App']['IsScanning']();
}

export function KillLaunch(arg1) {
  return window['go']['main']['App']['KillLaunch'](arg1);
}

export function LaunchProfile(arg1) {
  return window['go']['main']['App']['LaunchProfile'](arg1);
}

export function ListEngines() {
  return window['go']['main']['App']['ListEngines']();
}

export function ListIWADs() {
  return window['go']['main']['App']['ListIWADs']();
}

export function ListLaunchHistory(arg1) {
  return window['go']['main']['App']['ListLaunchHistory'](arg1);
}

export function ListMods(arg1) {
  return window['go']['main']['App']['ListMods'](arg1);
}

export function ListProfileSnapshots(arg1) {
  return window['go']['main']['App']['ListProfileSnapshots'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function OpenDirectoryDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1, arg2);
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2, arg3);
}

export function OpenPathInExplorer(arg1) {
  return window['go']['main']['App']['OpenPathInExplorer'](arg1);
}

export function OpenProfileSaveFolder(arg1) {
  return window['go']['main']['App']['OpenProfileSaveFolder'](arg1);
}

export function OrganizeDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['OrganizeDirectory'](arg1, arg2, arg3);
}

export function RegisterIWADFile(arg1) {
  return window['go']['main']['App']['RegisterIWADFile'](arg1);
}

export function RemoveModFromProfile(arg1, arg2) {
  return window['go']['main']['App']['RemoveModFromProfile'](arg1, arg2);
}

export function ReorderProfileMods(arg1, arg2) {
  return window['go']['main']['App']['ReorderProfileMods'](arg1, arg2);
}

export function RepairDiagnosticIssue(arg1, arg2) {
  return window['go']['main']['App']['RepairDiagnosticIssue'](arg1, arg2);
}

export function ReplayDemo(arg1) {
  return window['go']['main']['App']['ReplayDemo'](arg1);
}

export function RestoreProfileSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RestoreProfileSnapshot'](arg1, arg2);
}

export function RunDiagnostics() {
  return window['go']['main']['App']['RunDiagnostics']();
}

export function SearchIdgames(arg1) {
  return window['go']['main']['App']['SearchIdgames'](arg1);
}

export function SearchIdgamesCatalog(arg1) {
  return window['go']['main']['App']['SearchIdgamesCatalog'](arg1);
}

export function SetDBPath(arg1) {
  return window['go']['main']['App']['SetDBPath'](arg1);
}

export function SetEventEmitter(arg1) {
  return window['go']['main']['App']['SetEventEmitter'](arg1);
}

export function StartScan() {
  return window['go']['main']['App']['StartScan']();
}

export function SyncIdgamesHighWatermark() {
  return window['go']['main']['App']['SyncIdgamesHighWatermark']();
}

export function ToggleModFavorite(arg1) {
  return window['go']['main']['App']['ToggleModFavorite'](arg1);
}

export function ToggleProfileFavorite(arg1) {
  return window['go']['main']['App']['ToggleProfileFavorite'](arg1);
}

export function ToggleProfileMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleProfileMod'](arg1, arg2, arg3);
}

export function UpdateEngine(arg1) {
  return window['go']['main']['App']['UpdateEngine'](arg1);
}

export function UpdateIWAD(arg1) {
  return window['go']['main']['App']['UpdateIWAD'](arg1);
}

export function UpdateMod(arg1) {
  return window['go']['main']['App']['UpdateMod'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ValidateEngineExecutable(arg1) {
  return window['go']['main']['App']['ValidateEngineExecutable'](arg1);
}

export function ValidateProfile(arg1) {
  return window['go']['main']['App']['ValidateProfile'](arg1);
}
