// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {idgames} from '../models';
import {launcher} from '../models';
import {logger} from '../models';
import {filesystem} from '../models';

export function AddEngine(arg1:domain.Engine):Promise<domain.Engine>;

export function AddIWAD(arg1:domain.IWAD):Promise<domain.IWAD>;

export function AddModToProfile(arg1:string,arg2:string):Promise<void>;

export function ClearLaunchHistory():Promise<void>;

export function ClearSystemLogs():Promise<void>;

export function Close():Promise<void>;

export function CreateProfile(arg1:domain.Profile):Promise<domain.Profile>;

export function DeleteEngine(arg1:string):Promise<void>;

export function DeleteIWAD(arg1:string):Promise<void>;

export function DeleteMod(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DetectEngineVersion(arg1:string):Promise<Record<string, string>>;

export function DownloadIdgamesMod(arg1:idgames.IdgamesFile):Promise<domain.Mod>;

export function DuplicateProfile(arg1:string,arg2:string):Promise<domain.Profile>;

export function ExportProfileYAML(arg1:string):Promise<string>;

export function GetActiveLaunches():Promise<Array<launcher.ActiveLaunch>>;

export function GetEngine(arg1:string):Promise<domain.Engine>;

export function GetHistoryStats():Promise<domain.HistoryStats>;

export function GetIWAD(arg1:string):Promise<domain.IWAD>;

export function GetMod(arg1:string):Promise<domain.Mod>;

export function GetModArtwork(arg1:string):Promise<Record<string, any>>;

export function GetModUsageCounts():Promise<Record<string, number>>;

export function GetProfile(arg1:string):Promise<domain.Profile>;

export function GetProfileSaveDir(arg1:string):Promise<string>;

export function GetSettings():Promise<domain.Settings>;

export function GetSystemLogs():Promise<Array<logger.LogEntry>>;

export function ImportModFile(arg1:string):Promise<domain.Mod>;

export function ImportProfileYAML(arg1:string):Promise<Record<string, any>>;

export function ImportProfileZDL(arg1:string):Promise<Record<string, any>>;

export function InspectIWADFile(arg1:string):Promise<domain.IWAD>;

export function InspectMod(arg1:string):Promise<filesystem.FileInfo>;

export function IsScanning():Promise<boolean>;

export function KillLaunch(arg1:string):Promise<void>;

export function LaunchProfile(arg1:string):Promise<domain.LaunchRecord>;

export function ListEngines():Promise<Array<domain.Engine>>;

export function ListIWADs():Promise<Array<domain.IWAD>>;

export function ListLaunchHistory(arg1:number):Promise<Array<domain.LaunchRecord>>;

export function ListMods(arg1:domain.ModFilter):Promise<Array<domain.Mod>>;

export function ListProfiles():Promise<Array<domain.Profile>>;

export function OpenDirectoryDialog(arg1:string,arg2:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function OpenPathInExplorer(arg1:string):Promise<void>;

export function OpenProfileSaveFolder(arg1:string):Promise<void>;

export function RegisterIWADFile(arg1:string):Promise<domain.IWAD>;

export function RemoveModFromProfile(arg1:string,arg2:string):Promise<void>;

export function ReorderProfileMods(arg1:string,arg2:Array<string>):Promise<void>;

export function RepairDiagnosticIssue(arg1:string,arg2:string):Promise<void>;

export function RunDiagnostics():Promise<domain.DiagnosticsReport>;

export function SearchIdgames(arg1:string):Promise<Array<idgames.IdgamesFile>>;

export function SetDBPath(arg1:string):Promise<void>;

export function SetEventEmitter(arg1:any):Promise<void>;

export function StartScan():Promise<domain.ScanResult>;

export function ToggleModFavorite(arg1:string):Promise<boolean>;

export function ToggleProfileFavorite(arg1:string):Promise<void>;

export function ToggleProfileMod(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UpdateEngine(arg1:domain.Engine):Promise<void>;

export function UpdateIWAD(arg1:domain.IWAD):Promise<void>;

export function UpdateProfile(arg1:domain.Profile):Promise<void>;

export function UpdateSettings(arg1:domain.Settings):Promise<void>;

export function ValidateEngineExecutable(arg1:string):Promise<void>;

export function ValidateProfile(arg1:string):Promise<domain.ValidationResult>;
